Controllers/qBoConfigurationController.cs
//Copyright 2020 Alexey Prokhorov

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at

//    http://www.apache.org/licenses/LICENSE-2.0

//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

using Baroque.Plugin.Widgets.qBoSlider.Service.Sliders;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Core;
using Nop.Core.Infrastructure;
using Nop.Plugin.Widgets.qBoSlider.Models.Admin;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Widgets.qBoSlider.Controllers
{
    /// <summary>
    /// Represents plugin configuration controller
    /// </summary>
    [AuthorizeAdmin]
    [Area(AreaNames.ADMIN)]
    public class qBoConfigurationController : BasePluginController
    {
        #region Fields

        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly ISettingService _settingService;
        private readonly ITypeFinder _typeFinder;

        private readonly IStoreContext _storeContext;

        #endregion

        #region Constructor

        public qBoConfigurationController(ILocalizationService localizationService,
            INotificationService notificationService,
            ISettingService settingService,
            ITypeFinder typeFinder,
            IStoreContext storeContext)
        {
            _localizationService = localizationService;
            _notificationService = notificationService;
            _settingService = settingService;
            _typeFinder = typeFinder;
            _storeContext = storeContext;
        }

        #endregion

        #region Methods

        [CheckPermission(StandardPermission.Configuration.MANAGE_WIDGETS)]
        public virtual async Task<IActionResult> Configure()
        {
            var storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var settings = await _settingService.LoadSettingAsync<qBoSliderSettings>(storeScope);
            var availableSliders = _typeFinder.FindClassesOfType<ISlider>();

            var model = new ConfigurationModel()
            {
                ActiveStoreScopeConfiguration = storeScope,
                AvailableSliders = availableSliders.Select(x =>
                {
                    var instance = (ISlider)EngineContext.Current.Resolve(x);
                    return new SelectListItem()
                    {
                        Value = x.FullName,
                        Text = instance.Name,
                    };
                }).ToList(),
                UseStaticCache = settings.UseStaticCache,
                SelectedDefaultSliderSystemName = settings.SelectedDefaultSliderSystemName
            };

            return View("~/Plugins/Widgets.qBoSlider/Views/Admin/Configure.cshtml", model);
        }

        [HttpPost]
        [CheckPermission(StandardPermission.Configuration.MANAGE_WIDGETS)]
        public virtual async Task<IActionResult> Configure(ConfigurationModel model)
        {
            var storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var settings = await _settingService.LoadSettingAsync<qBoSliderSettings>(storeScope);

            settings.UseStaticCache = model.UseStaticCache;
            settings.SelectedDefaultSliderSystemName = model.SelectedDefaultSliderSystemName;

            await _settingService.SaveSettingAsync(settings, storeScope);

            //now clear settings cache
            await _settingService.ClearCacheAsync();

            _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Plugins.Saved"));

            return await Configure();
        }

        #endregion
    }
}

Views/Admin/Configure.cshtml
@{
    Layout = "_ConfigurePlugin";
}
@model ConfigurationModel


<form asp-controller="qBoConfiguration" asp-action="Configure" method="post">
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <div class="content-header clearfix">
                        <div class="ui-state-highlight ui-corner-all" style="margin-top:0;padding:10px">
                            <span class="ui-icon ui-icon-info" style="float:left;margin-right:.3em"></span>
                            qBoSlider extend nopCommerce menu and now you can edit slide collection from admin menu panel. <a target="_blank" href="/Admin/qBoSlide/List">Click here to edit <strong>SLIDES</strong></a>, and <a target="_blank" href="/Admin/qBoWidgetZone/List">here to edit <strong>WIDGET ZONES</strong></a>. <a target="_blank" href="https://github.com/iAlexeyProkhorov/qBoSlider/wiki/Get-started"><strong>Visit 'Get Started' page</strong>.</a>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="UseStaticCache" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="UseStaticCache" />
                        <span asp-validation-for="UseStaticCache"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <input type="submit" name="save" class="btn bg-blue" value="@T("Admin.Common.Save")" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Views/Admin/_SlideSearch.cshtml
@model ISlideSearchModel
@{
    const string hideSearchBlockAttributeName = "Baroque.qBoSlider.Slide.HideSearchBlock";
    var hideSearchBlock = await genericAttributeService.GetAttributeAsync<bool>(await workContext.GetCurrentCustomerAsync(), hideSearchBlockAttributeName);
}

<div class="card card-default card-search">
    <div class="card-body">
        <div class="row search-row @(!hideSearchBlock ? "opened" : "")" data-hideAttribute="@hideSearchBlockAttributeName">
            <div class="search-text">@T("Admin.Common.Search")</div>
            <div class="icon-search"><i class="fa fa-search" aria-hidden="true"></i></div>
            <div class="icon-collapse"><i class="fa fa-angle-down" aria-hidden="true"></i></div>
        </div>

        <div class="search-body @(hideSearchBlock ? "closed" : "")">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <div class="col-md-4">
                            <nop-label asp-for="SearchName" />
                        </div>
                        <div class="col-md-8">
                            <nop-editor asp-for="SearchName" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4">
                            <nop-label asp-for="SearchWidgetZoneId" />
                        </div>
                        <div class="col-md-8">
                            <nop-select asp-for="SearchWidgetZoneId" asp-items="@Model.AvailableWidgetZones" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4">
                            <nop-label asp-for="SearchStartDateOnUtc" />
                        </div>
                        <div class="col-md-8">
                            <nop-editor asp-for="SearchStartDateOnUtc" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4">
                            <nop-label asp-for="SearchFinishDateOnUtc" />
                        </div>
                        <div class="col-md-8">
                            <nop-editor asp-for="SearchFinishDateOnUtc" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4">
                            <nop-label asp-for="SearchPublicationStateId" />
                        </div>
                        <div class="col-md-8">
                            <nop-select asp-for="SearchPublicationStateId" asp-items="@Model.AvailablePublicationStates" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="text-center col-12">
                            <button type="button" id="search-slides" class="btn btn-primary btn-search">
                                <i class="fas fa-search"></i>
                                @T("Admin.Common.Search")
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Admin/_WidgetZoneSearch.cshtml
@model IWidgetZoneSearchModel
@{
    const string hideSearchBlockAttributeName = "Baroque.qBoSlider.WidgetZone.HideSearchBlock";
    var hideSearchBlock = await genericAttributeService.GetAttributeAsync<bool>(await workContext.GetCurrentCustomerAsync(), hideSearchBlockAttributeName);
}

<div class="card card-default card-search">
    <div class="card-body">
        <div class="row search-row @(!hideSearchBlock ? "opened" : "")" data-hideAttribute="@hideSearchBlockAttributeName">
            <div class="search-text">@T("Admin.Common.Search")</div>
            <div class="icon-search"><i class="fa fa-search" aria-hidden="true"></i></div>
            <div class="icon-collapse"><i class="fa fa-angle-down" aria-hidden="true"></i></div>
        </div>

        <div class="search-body @(hideSearchBlock ? "closed" : "")">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <div class="col-md-4">
                            <nop-label asp-for="SearchWidgetZoneName" />
                        </div>
                        <div class="col-md-8">
                            <nop-editor asp-for="SearchWidgetZoneName" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4">
                            <nop-label asp-for="SearchWidgetZoneSystemName" />
                        </div>
                        <div class="col-md-8">
                            <nop-editor asp-for="SearchWidgetZoneSystemName" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="text-center col-sm-12">
                            <button type="button" id="search-widget-zones" class="btn btn-primary btn-search">
                                <i class="fas fa-search"></i>
                                @T("Admin.Common.Search")
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Admin/_qBoLayout.cshtml
@using Nop.Plugin.Widgets.qBoSlider;
@using Nop.Plugin.Widgets.qBoSlider.Models.Admin;

@inject qBoSliderSettings settings;

@{
    Layout = "_AdminLayout";
}


@if (settings.UseStaticCache)
{
    <div class="content-header clearfix">
        <div class="ui-state-highlight ui-corner-all" style="margin-top:0;padding:10px">
            <span class="ui-icon ui-icon-info" style="float:left;margin-right:.3em"></span>
            @T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.DontForgetToClearSiteCacheToSeeYourSliderChanges")
        </div>
    </div>
}

@RenderBody()