Models/Admin/WidgetZones/AddWidgetZoneSlideModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Web.Framework.Models;
using Nop.Web.Framework.Mvc.ModelBinding;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Nop.Plugin.Widgets.qBoSlider.Models.Admin.WidgetZones
{
    /// <summary>
    /// Represents add widget zone slide model
    /// </summary>
    public record AddWidgetZoneSlideModel : BaseSearchModel, ISlideSearchModel
    {
        /// <summary>
        /// Gets or sets widget zone unique id number
        /// </summary>
        public int WidgetZoneId { get; set; }

        /// <summary>
        /// Gets or sets seleceted slides id numbers
        /// </summary>
        public IList<int> SelecetedSlideIds { get; set; } = new List<int>();

        /// <summary>
        /// Gets or sets slide search name
        /// </summary>
        [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.SlideSearch.SearchName")]
        public string SearchName { get; set; }

        /// <summary>
        /// Gets or sets search slide widget zone 
        /// </summary>
        [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.SlideSearch.SearchWidgetZoneId")]
        public int SearchWidgetZoneId { get; set; }

        /// <summary>
        /// Gets or sets available widget zones
        /// </summary>
        public IList<SelectListItem> AvailableWidgetZones { get; set; } = new List<SelectListItem>();

        /// <summary>
        /// Gets or sets slide search start date
        /// </summary>
        [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.SlideSearch.SearchStartDateOnUtc")]
        [UIHint("DateTimeNullable")]
        public DateTime? SearchStartDateOnUtc { get; set; }

        /// <summary>
        /// Gets or sets slide search finish date
        /// </summary>
        [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.SlideSearch.SearchFinishDateOnUtc")]
        [UIHint("DateTimeNullable")]
        public DateTime? SearchFinishDateOnUtc { get; set; }

        /// <summary>
        /// Gets or sets slide search publication status
        /// </summary>
        [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.SlideSearch.PublicationStateId")]
        public int SearchPublicationStateId { get; set; }

        /// <summary>
        /// Gets or sets list of available publication states
        /// </summary>
        public IList<SelectListItem> AvailablePublicationStates { get; set; } = new List<SelectListItem>();

        /// <summary>
        /// Represents slide list model
        /// </summary>
        public record SlidePagedListModel : BasePagedListModel<SlideModel>
        {

        }

        /// <summary>
        /// Represents slide for slide searching
        /// </summary>
        public record SlideModel : BaseNopEntityModel
        {
            /// <summary>
            /// Gets or sets slide background picture url
            /// </summary>
            [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.AddWidgetZoneSlide.Fields.PictureUrl")]
            public string PictureUrl { get; set; }

            /// <summary>
            /// Gets or sets slide search name
            /// </summary>
            [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.AddWidgetZoneSlide.Fields.Name")]
            public string Name { get; set; }

            /// <summary>
            /// Gets or sets slide publishing start date 
            /// </summary>
            [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.AddWidgetZoneSlide.Fields.StartDateUtc")]
            public DateTime? StartDateUtc { get; set; }

            /// <summary>
            /// Gets or sets slide publishing end date
            /// </summary>
            [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.AddWidgetZoneSlide.Fields.EndDateUtc")]
            public DateTime? EndDateUtc { get; set; }

            /// <summary>
            /// Gets or sets slide publish value
            /// </summary>
            [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.AddWidgetZoneSlide.Fields.Published")]
            public bool Published { get; set; }
        }
    }
}

Models/Admin/WidgetZones/WidgetZoneModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Web.Framework.Models;
using Nop.Web.Framework.Mvc.ModelBinding;
using System.Collections.Generic;

namespace Nop.Plugin.Widgets.qBoSlider.Models.Admin.WidgetZones
{
    /// <summary>
    /// Represents widget zone admin side model
    /// </summary>
    public partial record WidgetZoneModel : BaseNopEntityModel
    {
        /// <summary>
        /// Gets or sets the widget zone name
        /// </summary>
        [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.Fields.Name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets widget zone system name
        /// </summary>
        [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.Fields.SystemName")]
        public string SystemName { get; set; }

        /// <summary>
        /// Gets or sets slider extension system name
        /// </summary>
        public string SliderSystemName { get; set; }

        /// <summary>
        /// Gets or sets slide displaying for current widget zone. 'true' - display slider.
        /// </summary>
        [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.Fields.Published")]
        public bool Published { get; set; }

        /// <summary>
        /// Gets or sets selected customer role ids
        /// </summary>
        [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.Fields.SelectedCustomerRoleIds")]
        public IList<int> SelectedCustomerRoleIds { get; set; } = new List<int>();

        /// <summary>
        /// Gets or sets available customer roles
        /// </summary>
        public IList<SelectListItem> AvailableCustomerRoles { get; set; } = new List<SelectListItem>();

        /// <summary>
        /// Gets or sets selected store entities ids
        /// </summary>
        [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.Fields.SelectedStoreIds")]
        public IList<int> SelectedStoreIds { get; set; } = new List<int>();

        /// <summary>
        /// Gets or sets available stores
        /// </summary>
        public IList<SelectListItem> AvailableStores { get; set; } = new List<SelectListItem>();

        /// <summary>
        /// Gets or sets slide search model
        /// </summary>
        public WidgetZoneSlideSearchModel SlideSearchModel { get; set; } = new WidgetZoneSlideSearchModel();
    }
}

Controllers/qBoWidgetZoneController.cs
//Copyright 2020 Alexey Prokhorov

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at

//    http://www.apache.org/licenses/LICENSE-2.0

//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

using Baroque.Plugin.Widgets.qBoSlider.Service;
using Baroque.Plugin.Widgets.qBoSlider.Sliders.Jssor;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Caching;
using Nop.Plugin.Widgets.qBoSlider.Domain;
using Nop.Plugin.Widgets.qBoSlider.Factories.Admin;
using Nop.Plugin.Widgets.qBoSlider.Models.Admin.WidgetZones;
using Nop.Plugin.Widgets.qBoSlider.Service;
using Nop.Services.Configuration;
using Nop.Services.Customers;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Services.Stores;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Widgets.qBoSlider.Controllers
{
    /// <summary>
    /// Represents plugin widget zone controller
    /// </summary>
    [AuthorizeAdmin]
    [Area(AreaNames.ADMIN)]
    public class qBoWidgetZoneController : BasePluginController
    {
        #region Fields

        private readonly IAclService _aclService;
        private readonly ICustomerService _customerService;
        private readonly ILocalizationService _localizationService;
        private readonly ILocalizedEntityService _localizedEntityService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly ISearchModelFactory _searchModelFactory;
        private readonly ISettingService _settingService;
        private readonly IStaticCacheManager _staticCacheManager;
        private readonly IStoreMappingService _storeMappingService;
        private readonly IStoreContext _storeContext;
        private readonly IStoreService _storeService;
        private readonly IWidgetZoneModelFactory _widgetZoneModelFactory;
        private readonly IWidgetZoneSlideModelFactory _widgetZoneSlideModelFactory;
        private readonly IWidgetZoneService _widgetZoneService;
        private readonly IWidgetZoneSlideService _widgetZoneSlideService;
        private readonly IWidgetZoneSliderPropertyService _widgetZoneSliderPropertyService;

        #endregion

        #region Constructor

        public qBoWidgetZoneController(IAclService aclService,
            ICustomerService customerService,
            ILocalizationService localizationService,
            ILocalizedEntityService localizedEntityService,
            INotificationService notificationService,
            IPermissionService permissionService,
            ISearchModelFactory searchModelFactory,
            ISettingService settingService,
            IStoreMappingService storeMappingService,
            IStoreContext storeContext,
            IStoreService storeService,
            IWidgetZoneModelFactory widgetZoneModelFactory,
            IWidgetZoneSlideModelFactory widgetZoneSlideModelFactory,
            IWidgetZoneService widgetZoneService,
            IWidgetZoneSlideService widgetZoneSlideService,
            IWidgetZoneSliderPropertyService widgetZoneSliderPropertyService)
        {
            _aclService = aclService;
            _customerService = customerService;
            _localizationService = localizationService;
            _localizedEntityService = localizedEntityService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _searchModelFactory = searchModelFactory;
            _settingService = settingService;
            _storeMappingService = storeMappingService;
            _storeContext = storeContext;
            _storeService = storeService;
            _widgetZoneModelFactory = widgetZoneModelFactory;
            _widgetZoneSlideModelFactory = widgetZoneSlideModelFactory;
            _widgetZoneService = widgetZoneService;
            _widgetZoneSlideService = widgetZoneSlideService;
            _widgetZoneSliderPropertyService = widgetZoneSliderPropertyService;
        }

        #endregion

        #region Utilites

        /// <summary>
        /// Save widget zone ACL
        /// </summary>
        /// <param name="model">Widget zone model</param>
        /// <param name="widgetZone">Widget zone entity</param>
        protected virtual async Task SaveWidgetZoneAcl(WidgetZoneModel model, WidgetZone widgetZone)
        {
            var existingAclRecords = await _aclService.GetAclRecordsAsync(widgetZone);
            var allCustomerRoles = await _customerService.GetAllCustomerRolesAsync(true);

            //processing customer roles dependencies
            foreach (var customerRole in allCustomerRoles)
            {
                if (model.SelectedCustomerRoleIds.Contains(customerRole.Id))
                {
                    //add new role dependecy
                    if (existingAclRecords.Count(acl => acl.CustomerRoleId == customerRole.Id) == 0)
                        await _aclService.InsertAclRecordAsync(widgetZone, customerRole.Id);
                }
                else
                {
                    //remove role dependency
                    var aclRecordToDelete = existingAclRecords.FirstOrDefault(acl => acl.CustomerRoleId == customerRole.Id);
                    if (aclRecordToDelete != null)
                        await _aclService.DeleteAclRecordAsync(aclRecordToDelete);
                }
            }
        }

        /// <summary>
        /// Save widget zone store mappings
        /// </summary>
        /// <param name="model">Widget zone model</param>
        /// <param name="widgetZone">Widget zone entity</param>
        protected virtual async Task SaveWidgetZoneStoreMappings(WidgetZoneModel model, WidgetZone widgetZone)
        {
            var existingStoreMappings = await _storeMappingService.GetStoreMappingsAsync(widgetZone);
            var allStores = await _storeService.GetAllStoresAsync();

            //process store mappings
            foreach (var store in allStores)
            {
                if (model.SelectedStoreIds.Contains(store.Id))
                {
                    //add new store mapping
                    if (existingStoreMappings.Count(sm => sm.StoreId == store.Id) == 0)
                        await _storeMappingService.InsertStoreMappingAsync(widgetZone, store.Id);
                }
                else
                {
                    //remove store mapping
                    var storeMappingToDelete = existingStoreMappings.FirstOrDefault(sm => sm.StoreId == store.Id);
                    if (storeMappingToDelete != null)
                        await _storeMappingService.DeleteStoreMappingAsync(storeMappingToDelete);
                }
            }
        }

        #endregion

        #region Widget Zone

        [CheckPermission(StandardPermission.Configuration.MANAGE_WIDGETS)]
        public virtual async Task<IActionResult> List()
        {
            var model = new WidgetZoneSearchModel();
            model.SetGridPageSize();

            return View("~/Plugins/Widgets.qBoSlider/Views/Admin/WidgetZone/List.cshtml", model);
        }

        [HttpPost]
        [CheckPermission(StandardPermission.Configuration.MANAGE_WIDGETS, CheckPermissionAttribute.CheckPermissionResultType.Json)]
        public virtual async Task<IActionResult> List(WidgetZoneSearchModel searchModel)
        {
            var gridModel = await _widgetZoneModelFactory.PrepareWidgetZonePagedListModelAsync(searchModel);

            return Json(gridModel);
        }

        [CheckPermission(StandardPermission.Configuration.MANAGE_WIDGETS)]
        public virtual async Task<IActionResult> Create()
        {
            var storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var settings = await _settingService.LoadSettingAsync<qBoSliderSettings>(storeScope);
            var model = new WidgetZoneModel()
            {
                SliderSystemName = settings.SelectedDefaultSliderSystemName,
                //ArrowNavigationDisplayingTypeId = (int)NavigationType.OnMouseDrag,
                //BulletNavigationDisplayingTypeId = (int)NavigationType.Always,
                //SliderAlignmentId = (int)SliderAlignment.Center,
            };

            //prepare widget zone model
            await _widgetZoneModelFactory.PrepareWidgetZoneModelAsync(model, null);
            //prepare widget zone ACL
            await _widgetZoneModelFactory.PrepareAclModelAsync(model, null);
            //prepare widget zone store mappings
            await _widgetZoneModelFactory.PrepareStoreMappingsAsync(model, null);

            return View("~/Plugins/Widgets.qBoSlider/Views/Admin/WidgetZone/Create.cshtml", model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        [CheckPermission(StandardPermission.Configuration.MANAGE_WIDGETS)]
        public virtual async Task<IActionResult> Create(WidgetZoneModel model, bool continueEditing)
        {
            //return view if model state isn't valid
            if (!ModelState.IsValid)
            {
                //prepare model values
                model = await _widgetZoneModelFactory.PrepareWidgetZoneModelAsync(model, null);
                //prepare widget zone ACL
                await _widgetZoneModelFactory.PrepareAclModelAsync(model, null);
                //prepare widget zone store mappings
                await _widgetZoneModelFactory.PrepareStoreMappingsAsync(model, null);

Views/Admin/WidgetZone/AddWidgetZoneSlidePopup.cshtml
@model AddWidgetZoneSlideModel

@{
    Layout = "_AdminPopupLayout";

    //page title
    ViewBag.Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.AddWidgetZoneSlidePopup").Text;
}

@if (ViewBag.RefreshPage == true)
{
    <script>
        try {window.opener.document.forms['@(Context.Request.Query["formId"])'].@(Context.Request.Query["btnId"]).click();}
        catch (e){}
        window.close();
    </script>
}
else
{
    <form asp-controller="qBoWidgetZone" asp-action="AddWidgetZoneSlidePopup"
          asp-route-categoryId="@Context.Request.Query["widgetZoneId"]"
          asp-route-btnId="@Context.Request.Query["btnId"]"
          asp-route-formId="@Context.Request.Query["formId"]">

        <input asp-for="WidgetZoneId" type="hidden" />
        <div class="content-header clearfix">
            <h1 class="pull-left">
                @T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.WidgetZoneSlide.AddNew")
            </h1>
            <div class="pull-right">
                &nbsp;
            </div>
        </div>
        <section class="content">
            <div class="form-horizontal">
                <div class="cards-group">
                    @await Html.PartialAsync("~/Plugins/Widgets.qBoSlider/Views/Admin/_SlideSearch.cshtml", Model)
                    <div class="card card-default">
                        <div class="card-body">
                            @await  Html.PartialAsync("Table", new DataTablesModel
                       {
                           Name = "slides-grid",
                           UrlRead = new DataUrl("AddSlideList", "qBoWidgetZone", null),
                           Length = Model.PageSize,
                           LengthMenu = Model.AvailablePageSizes,
                           ColumnCollection = new List<ColumnProperty>
                                   {
                                       new ColumnProperty(nameof(AddWidgetZoneSlideModel.SlideModel.Id))
                                       {
                                           IsMasterCheckBox = true,
                                           Render = new RenderCheckBox(nameof(AddWidgetZoneSlideModel.SelecetedSlideIds)),
                                           ClassName = NopColumnClassDefaults.CenterAll,
                                           Width = "50"
                                       },
                                       new ColumnProperty(nameof(AddWidgetZoneSlideModel.SlideModel.PictureUrl))
                                       {
                                           Render = new RenderPicture(),
                                           ClassName = NopColumnClassDefaults.CenterAll,
                                           Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.AddWidgetZoneSlide.Fields.PictureUrl").Text,
                                           Width = "300"
                                       },
                                       new ColumnProperty(nameof(AddWidgetZoneSlideModel.SlideModel.Name))
                                       {
                                           Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.AddWidgetZoneSlide.Fields.Name").Text
                                       },
                                       new ColumnProperty(nameof(AddWidgetZoneSlideModel.SlideModel.StartDateUtc))
                                       {
                                           Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.AddWidgetZoneSlide.Fields.StartDateUtc").Text,
                                           Render = new RenderDate(),
                                           Width = "150"
                                       },
                                       new ColumnProperty(nameof(AddWidgetZoneSlideModel.SlideModel.EndDateUtc))
                                       {
                                           Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.AddWidgetZoneSlide.Fields.EndDateUtc").Text,
                                           Render = new RenderDate(),
                                           Width = "150"
                                       },
                                       new ColumnProperty(nameof(AddWidgetZoneSlideModel.SlideModel.Published))
                                       {
                                           Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.AddWidgetZoneSlide.Fields.Published").Text,
                                           Render = new RenderBoolean(),
                                           ClassName = NopColumnClassDefaults.CenterAll,
                                           Width = "100"
                                       }
                                   }
                       })
                        </div>
                        <div class="card-footer">
                            <button type="submit" name="save" class="btn btn-primary">
                                <i class="far fa-save"></i>
                                @T("Admin.Common.Save")
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </form>
}

Views/Admin/WidgetZone/Create.cshtml
@model WidgetZoneModel
@{
    //page title
    ViewBag.Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.Create").Text;
    //active menu item (system name)
    nopHtml.SetActiveMenuItemSystemName("Baroque-qBoSlider-WidgetZone");
    Layout = "_AdminLayout";
}

<form asp-controller="qBoWidgetZone" asp-action="Create" method="post" id="widget-zone-form">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.Create")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = "qBo_slider_widget_create_buttons" })
        </div>
    </div>
    <div class="content-header clearfix">
        <div class="ui-state-highlight ui-corner-all" style="margin-top:0;padding:10px">
            <span class="ui-icon ui-icon-info" style="float:left;margin-right:.3em"></span>
            @T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.ClearNopCommerceWidgetZoneAfterNewWidgetZoneCreation")
        </div>
    </div>
    @await Html.PartialAsync("~/Plugins/Widgets.qBoSlider/Views/Admin/WidgetZone/_CreateOrUpdate.cshtml", Model)
</form>

Views/Admin/WidgetZone/CreateWidgetZone.cshtml
@model WidgetZoneModel
@{
    //page title
    ViewBag.Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.Create").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Baroque-qBoSlider-WidgetZone");
    Layout = "_AdminLayout";
}

<form asp-controller="qBoWidgetZone" asp-action="CreateWidgetZone" method="post" id="widget-zone-form">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.Create")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = "qBo_slider_widget_create_buttons" })
        </div>
    </div>
    @await Html.PartialAsync("~/Plugins/Widgets.qBoSlider/Views/Admin/WidgetZone/_CreateOrUpdate.cshtml", Model)
</form>

Views/Admin/WidgetZone/Edit.cshtml
@model WidgetZoneModel
@{
    //page title
    ViewBag.Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.Edit").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Baroque-qBoSlider-WidgetZone");
    Layout = "~/Plugins/Widgets.qBoSlider/Views/Admin/_qBoLayout.cshtml";
}

<form asp-controller="qBoWidgetZone" asp-action="Edit" method="post" id="widget-zone-form">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.Edit") - @Model.Name
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="widget-zone-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = "qBo_slider_widget_edit_buttons" })
        </div>
    </div>
    @await Html.PartialAsync("~/Plugins/Widgets.qBoSlider/Views/Admin/WidgetZone/_CreateOrUpdate.cshtml", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="widget-zone-delete" />

Views/Admin/WidgetZone/_CreateOrUpdate.Mappings.cshtml
@model WidgetZoneModel


<div class="card-body">
    <div class="form-group row">
        <div class="col-md-3">
            <nop-label asp-for="SelectedCustomerRoleIds" />
        </div>
        <div class="col-md-9">
            <div class="row">
                <div class="col-md-4">
                    <nop-select asp-for="SelectedCustomerRoleIds" asp-items="Model.AvailableCustomerRoles" asp-multiple="true" />
                    <script>
						$(document).ready(function() {
							var rolesIdsInput = $('#@Html.IdFor(model => model.SelectedCustomerRoleIds)')
								.data("kendoMultiSelect");
							rolesIdsInput.setOptions({
								autoClose: false,
								filter: "contains"
							});

							@if (Model.AvailableCustomerRoles.Count == 0)
				{
					<text>
						rolesIdsInput.setOptions({
							enable: false,
							placeholder: 'No customer roles available'
						});
						rolesIdsInput._placeholder();
						rolesIdsInput._enable();
					</text>
				}
						});
                    </script>
                </div>
                <div class="col-md-8">
                    @await Component.InvokeAsync("AclDisabledWarning")
                </div>
            </div>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-3">
            <nop-label asp-for="SelectedStoreIds" />
        </div>
        <div class="col-md-9">
            <div class="row">
                <div class="col-md-4">
                    <nop-select asp-for="SelectedStoreIds" asp-items="Model.AvailableStores" asp-multiple="true" />
                    <script>
						$(document).ready(function() {
							var storesIdsInput = $('#@Html.IdFor(model => model.SelectedStoreIds)')
								.data("kendoMultiSelect");
							storesIdsInput.setOptions({
								autoClose: false,
								filter: "contains"
							});

							@if (Model.AvailableStores.Count == 0)
						{
							<text>
								storesIdsInput.setOptions({
									enable: false,
									placeholder: 'No stores available'
								});
								storesIdsInput._placeholder();
								storesIdsInput._enable();
							</text>
						}
						});
                    </script>
                </div>
                <div class="col-md-8">
                    @await Component.InvokeAsync("MultistoreDisabledWarning")
                </div>
            </div>
        </div>
    </div>
</div>