Models/Admin/Slides/AddSlideWidgetZoneModel.cs
//Copyright 2020 Alexey Prokhorov

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at

//    http://www.apache.org/licenses/LICENSE-2.0

//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

using Nop.Web.Framework.Models;
using System.Collections.Generic;

namespace Nop.Plugin.Widgets.qBoSlider.Models.Admin.Slides
{
    /// <summary>
    /// Represents add widget zone for slide editing
    /// </summary>
    public record AddSlideWidgetZoneModel : BaseSearchModel, IWidgetZoneSearchModel
    {
        /// <summary>
        /// Gets or sets slide entity id
        /// </summary>
        public int SlideId { get; set; }

        /// <summary>
        /// Gets or sets searching widget zone friendly name
        /// </summary>
        public string SearchWidgetZoneName { get; set; }

        /// <summary>
        /// Gets or sets searching widget zone system name
        /// </summary>
        public string SearchWidgetZoneSystemName { get; set; }

        /// <summary>
        /// Gets or sets selected widget zone id numbers
        /// </summary>
        public IList<int> SelectedWidgetZoneIds { get; set; } = new List<int>();

        public record WidgetZonePagedList: BasePagedListModel<WidgetZoneModel>
        {

        }

        /// <summary>
        /// Represents widget zone model for slide editing
        /// </summary>
        public record WidgetZoneModel : BaseNopEntityModel, ISlideWidgetZoneModel
        {
            /// <summary>
            /// Gets or sets widget zone friendly name
            /// </summary>
            public string Name { get; set; }

            /// <summary>
            /// Gets or sets widget zone system name
            /// </summary>
            public string SystemName { get; set; }

            /// <summary>
            /// Gets or sets value indicating widget zone availability
            /// </summary>
            public bool Published { get; set; }
        }
    }
}

Models/Admin/Slides/EditSlideWidgetZoneModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Web.Framework.Models;
using Nop.Web.Framework.Mvc.ModelBinding;
using System.Collections.Generic;

namespace Nop.Plugin.Widgets.qBoSlider.Models.Admin.Slides
{
    /// <summary>
    /// Represents slide widget zone editing model
    /// </summary>
    public record EditSlideWidgetZoneModel : BaseNopEntityModel, ILocalizedModel<EditSlideWidgetZoneModel.LocalizationModel>
    {
        /// <summary>
        /// Gets or sets slide id number
        /// </summary>
        public int SlideId { get; set; }

        /// <summary>
        /// Gets or sets widget zone id number
        /// </summary>
        [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.SlideWidgetZone.Fields.WidgetZoneId")]
        public int WidgetZoneId { get; set; }

        /// <summary>
        /// Gets or sets list of available widget zones
        /// </summary>
        public IList<SelectListItem> AvailableWidgetZones { get; set; } = new List<SelectListItem>();

        /// <summary>
        /// Gets or sets overrideble HTML description
        /// </summary>
        [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.SlideWidgetZone.Fields.OverrideDescription")]
        public string OverrideDescription { get; set; }

        /// <summary>
        /// Gets or sets slide widget zone localized values
        /// </summary>
        public IList<LocalizationModel> Locales { get; set; } = new List<LocalizationModel>();

        /// <summary>
        /// Represents widget zone slide overriding HTML content localization model
        /// </summary>
        public class LocalizationModel : ILocalizedLocaleModel
        {
            /// <summary>
            /// Gets or sets slide localized HTML content. 
            /// </summary>
            [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.SlideWidgetZone.Fields.OverrideDescription")]
            public string OverrideDescription { get; set; }

            /// <summary>
            /// Gets or sets the language identifier
            /// </summary>
            public int LanguageId { get; set; }
        }
    }
}

Models/Admin/Slides/ISlideWidgetZoneModel.cs
namespace Nop.Plugin.Widgets.qBoSlider.Models.Admin.Slides
{
    /// <summary>
    /// Represents slide widget model list item interface
    /// </summary>
    public interface ISlideWidgetZoneModel
    {
        /// <summary>
        /// Gets or sets widget zone friendly name
        /// </summary>
        string Name { get; set; }

        /// <summary>
        /// Gets or sets widget zone system name
        /// </summary>
        string SystemName { get; set; }

        /// <summary>
        /// Gets or sets value indicating widget zone availability
        /// </summary>
        bool Published { get; set; }
    }
}

Models/Admin/Slides/SlideSearchModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Web.Framework.Models;
using Nop.Web.Framework.Mvc.ModelBinding;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Nop.Plugin.Widgets.qBoSlider.Models.Admin.Slides
{
    /// <summary>
    /// Represent slide search model
    /// </summary>
    public record SlideSearchModel : BaseSearchModel, ISlideSearchModel
    {
        public string SearchName { get; set; }

        public int SearchWidgetZoneId { get; set; }

        public IList<SelectListItem> AvailableWidgetZones { get; set; } = new List<SelectListItem>();

        [UIHint("DateTimeNullable")]
        public DateTime? SearchStartDateOnUtc { get; set; }

        [UIHint("DateTimeNullable")]
        public DateTime? SearchFinishDateOnUtc { get; set; }

        public int SearchPublicationStateId { get; set; }

        public IList<SelectListItem> AvailablePublicationStates { get; set; } = new List<SelectListItem>();

        /// <summary>
        /// Represent slide page list model
        /// </summary>
        public record SlidePagedListModel :BasePagedListModel<SlideListItemModel>
        {

        }

        /// <summary>
        /// Represents slide in list
        /// </summary>
        public record SlideListItemModel : BaseNopEntityModel
        {
            /// <summary>
            /// Gets or sets slide picture Url
            /// </summary>
            public string Picture { get; set; }

            /// <summary>
            /// Gets or sets slide name
            /// </summary>
            public string Name { get; set; }

            /// <summary>
            /// Gets or sets slide hyperlink
            /// </summary>
            public string Hyperlink { get; set; }

            /// <summary>
            /// Gets or sets slide displaying start date
            /// </summary>
            public DateTime? StartDateUtc { get; set; }

            /// <summary>
            /// Gets or sets slide displaying end date
            /// </summary>
            public DateTime? EndDateUtc { get; set; }

            /// <summary>
            /// Gest or sets slide published or not
            /// </summary>
            public bool Published { get; set; }
        }
    }
}

Controllers/qBoSlideController.cs
//Copyright 2020 Alexey Prokhorov

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at

//    http://www.apache.org/licenses/LICENSE-2.0

//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Plugin.Widgets.qBoSlider.Domain;
using Nop.Plugin.Widgets.qBoSlider.Factories.Admin;
using Nop.Plugin.Widgets.qBoSlider.Models.Admin.Slides;
using Nop.Plugin.Widgets.qBoSlider.Service;
using Nop.Services.Configuration;
using Nop.Services.Customers;
using Nop.Services.Localization;
using Nop.Services.Media;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Services.Stores;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Widgets.qBoSlider.Controllers
{
    /// <summary>
    /// Represents plugin slide controller
    /// </summary>
    [AuthorizeAdmin]
    [Area(AreaNames.ADMIN)]
    [AutoValidateAntiforgeryToken]
    public class qBoSlideController : BasePluginController
    {
        #region Fields

        private readonly IAclService _aclService;
        private readonly ICustomerService _customerService;
        private readonly IGarbageManager _garbageManager;
        private readonly ILocalizationService _localizationService;
        private readonly ILocalizedEntityService _localizedEntityService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly IPictureService _pictureService;
        private readonly ISearchModelFactory _searchModelFactory;
        private readonly ISettingService _settingService;
        private readonly ISlideModelFactory _slideModelFactory;
        private readonly ISlideWidgetZoneModelFactory _slideWidgetZoneModelFactory;
        private readonly ISlideService _slideService;
        private readonly IStoreService _storeService;
        private readonly IStoreMappingService _storeMappingService;
        private readonly IWidgetZoneSlideService _widgetZoneSlideService;

        private readonly IStoreContext _storeContext;
        private readonly IWorkContext _workContext;

        #endregion

        #region Constructor

        public qBoSlideController(IAclService aclService,
            ICustomerService customerService,
            IGarbageManager garbageManager,
            ILocalizationService localizationService,
            ILocalizedEntityService localizedEntityService,
            INotificationService notificationService,
            IPermissionService permissionService,
            IPictureService pictureService,
            ISearchModelFactory searchModelFactory,
            ISettingService settingService,
            ISlideModelFactory slideModelFactory,
            ISlideWidgetZoneModelFactory slideWidgetZoneModelFactory,
            ISlideService slideService,
            IStoreService storeService,
            IStoreMappingService storeMappingService,
            IWidgetZoneSlideService widgetZoneSlideService,
            IStoreContext storeContext,
            IWorkContext workContext)
        {
            ForseDefaultCulture();

            this._aclService = aclService;
            this._customerService = customerService;
            this._garbageManager = garbageManager;
            this._localizationService = localizationService;
            this._localizedEntityService = localizedEntityService;
            this._notificationService = notificationService;
            this._permissionService = permissionService;
            _searchModelFactory = searchModelFactory;
            this._pictureService = pictureService;
            this._settingService = settingService;
            this._slideModelFactory = slideModelFactory;
            this._slideWidgetZoneModelFactory = slideWidgetZoneModelFactory;
            this._slideService = slideService;
            this._storeService = storeService;
            this._storeMappingService = storeMappingService;
            this._widgetZoneSlideService = widgetZoneSlideService;

            this._storeContext = storeContext;
            this._workContext = workContext;
        }

        #endregion

        #region Utilites

        protected virtual void ForseDefaultCulture()
        {
            //CommonHelper.SetTelerikCulture();
        }

        protected virtual async Task UpdateSlideLocalesAsync(Slide slide, SlideModel model)
        {
            foreach (var localized in model.Locales)
            {
                var pictureId = await _localizationService.GetLocalizedAsync(slide, x => x.PictureId, localized.LanguageId, false, false);
                await _localizedEntityService.SaveLocalizedValueAsync(slide, x => x.Description,
                    localized.Description,
                    localized.LanguageId);
                await _localizedEntityService.SaveLocalizedValueAsync(slide, x => x.HyperlinkAddress,
                    localized.Hyperlink,
                    localized.LanguageId);
                if (localized.PictureId > 0)
                    await _localizedEntityService.SaveLocalizedValueAsync(slide, x => x.PictureId,
                        localized.PictureId,
                        localized.LanguageId);
                else
                    if (pictureId.HasValue && localized.PictureId == 0)
                    await _localizedEntityService.SaveLocalizedValueAsync(slide, x => x.PictureId,
                        null,
                        localized.LanguageId);

                //if localized picture was changed
                //plugin remove old picture from database, because it will not needs in future
                if (pictureId != localized.PictureId)
                {
                    var picture = await _pictureService.GetPictureByIdAsync(pictureId.GetValueOrDefault(0));
                    if (picture != null)
                        await _pictureService.DeletePictureAsync(picture);
                }
            }
        }

        protected virtual async Task UpdateStoreMappingAsync(Slide slide, SlideModel model)
        {
            var allStores = await _storeService.GetAllStoresAsync();
            var limitedToStores = await _storeMappingService.GetStoreMappingsAsync(slide);

            foreach (var store in allStores)
            {
                if (model.SelectedStoreIds != null && model.SelectedStoreIds.Contains(store.Id))
                {
                    //new store mapping
                    if (!limitedToStores.Any(x => x.StoreId == store.Id))
                        await _storeMappingService.InsertStoreMappingAsync(slide, store.Id);
                }
                else
                {
                    //delete mapping
                    var storeMapping = limitedToStores.FirstOrDefault(x => x.StoreId == store.Id);
                    if (storeMapping != null)
                        await _storeMappingService.DeleteStoreMappingAsync(storeMapping);
                }
            }
        }

        protected virtual async Task SaveCustomerRolesAclAsync(Slide slide, SlideModel model)
        {
            var existingAclRecords = await _aclService.GetAclRecordsAsync(slide);
            var allCustomerRoles = await _customerService.GetAllCustomerRolesAsync(true);
            foreach (var customerRole in allCustomerRoles)
            {
                if (model.SelectedCustomerRoleIds.Contains(customerRole.Id))
                {
                    //new role
                    if (existingAclRecords.Count(acl => acl.CustomerRoleId == customerRole.Id) == 0)
                        await _aclService.InsertAclRecordAsync(slide, customerRole.Id);
                }
                else
                {
                    //remove role
                    var aclRecordToDelete = existingAclRecords.FirstOrDefault(acl => acl.CustomerRoleId == customerRole.Id);
                    if (aclRecordToDelete != null)
                        await _aclService.DeleteAclRecordAsync(aclRecordToDelete);
                }
            }
        }

        #endregion

        #region Slides List / Create / Update / Delete 

        public virtual async Task<IActionResult> List()
        {
            var model = new SlideSearchModel();
            await _searchModelFactory.PrepareSlideSearchModelAsync(model);

            return View("~/Plugins/Widgets.qBoSlider/Views/Admin/Slide/List.cshtml", model);
        }

        [HttpPost]
        [CheckPermission(StandardPermission.Configuration.MANAGE_WIDGETS)]
        public virtual async Task<IActionResult> List(SlideSearchModel searchModel)
        {
            var gridModel = await _slideModelFactory.PrepareSlideListPagedModelAsync(searchModel);

            return Json(gridModel);
        }

        [CheckPermission(StandardPermission.Configuration.MANAGE_WIDGETS)]
        public virtual async Task<IActionResult> Create()
        {
            var model = new SlideModel();
            await _slideModelFactory.PrepareSlideModelAsync(model, null);

            return View("~/Plugins/Widgets.qBoSlider/Views/Admin/Slide/Create.cshtml", model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        [CheckPermission(StandardPermission.Configuration.MANAGE_WIDGETS)]
        public virtual async Task<IActionResult> Create(SlideModel model, bool continueEditing)
        {
            //return on slide creation page if model invalid
            if (!ModelState.IsValid)
            {
                //prepare model mappings

Views/Admin/Slide/AddSlideWidgetZonePopup.cshtml
@model AddSlideWidgetZoneModel

@{
    Layout = "_AdminPopupLayout";

    //page title
    ViewBag.Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.Slide.AddSlideWidgetZonePopup").Text;
}

@if (ViewBag.RefreshPage == true)
{
    <script>
        try {window.opener.document.forms['@(Context.Request.Query["formId"])'].@(Context.Request.Query["btnId"]).click();}
        catch (e){}
        window.close();
    </script>
}
else
{
    <form asp-controller="qBoSlide" asp-action="AddSlideWidgetZonePopup"
          asp-route-categoryId="@Context.Request.Query["slideId"]"
          asp-route-btnId="@Context.Request.Query["btnId"]"
          asp-route-formId="@Context.Request.Query["formId"]">

        <input asp-for="SlideId" type="hidden" />
        <div class="content-header clearfix">
            <h1 class="pull-left">
                @T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.Slide.SlideWidgetZone.AddNew")
            </h1>
            <div class="pull-right">
                &nbsp;
            </div>
        </div>
        <section class="content">
            <div class="form-horizontal">
                <div class="cards-group">
                    @await Html.PartialAsync("~/Plugins/Widgets.qBoSlider/Views/Admin/_WidgetZoneSearch.cshtml", Model)
                    <div class="card card-default">
                        <div class="card-body">
                            @await  Html.PartialAsync("Table", new DataTablesModel
                       {
                           Name = "widget-zones-grid",
                           UrlRead = new DataUrl("GetWidgetZoneListPopup", "qBoSlide", null),
                           SearchButtonId = "search-widget-zones",
                           Length = Model.PageSize,
                           LengthMenu = Model.AvailablePageSizes,
                           Filters = new List<FilterParameter>
                                   {
                                       new FilterParameter(nameof(Model.SearchWidgetZoneName)),
                                       new FilterParameter(nameof(Model.SearchWidgetZoneSystemName))
                                   },
                           ColumnCollection = new List<ColumnProperty>
                                   {
                                       new ColumnProperty(nameof(AddSlideWidgetZoneModel.WidgetZoneModel.Id))
                                       {
                                           IsMasterCheckBox = true,
                                           Render = new RenderCheckBox(nameof(AddSlideWidgetZoneModel.SelectedWidgetZoneIds)),
                                           ClassName = NopColumnClassDefaults.CenterAll,
                                           Width = "50"
                                       },
                                       new ColumnProperty(nameof(AddSlideWidgetZoneModel.WidgetZoneModel.Name))
                                       {
                                           ClassName = NopColumnClassDefaults.CenterAll,
                                           Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.AddSlideWidgetZone.Fields.Name").Text,
                                           Width = "300"
                                       },
                                       new ColumnProperty(nameof(AddSlideWidgetZoneModel.WidgetZoneModel.SystemName))
                                       {
                                           Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.AddSlideWidgetZone.Fields.SystemName").Text,
                                           Width = "150"
                                       },
                                       new ColumnProperty(nameof(AddSlideWidgetZoneModel.WidgetZoneModel.Published))
                                       {
                                           Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.AddSlideWidgetZone.Fields.Published").Text,
                                           Width = "150",
                                           Render = new RenderBoolean(),
                                           ClassName = NopColumnClassDefaults.CenterAll
                                       }
                                   }
                       })
                        </div>
                        <div class="card-footer">
                            <button type="submit" name="save" class="btn btn-primary">
                                <i class="far fa-save"></i>
                                @T("Admin.Common.Save")
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </form>
}

Views/Admin/Slide/Create.cshtml
@model SlideModel

@{
    //page title
    ViewBag.Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.Slide.Create").Text;
    //active menu item (system name)
    nopHtml.SetActiveMenuItemSystemName("Baroque-qBoSlider-Slide");
    Layout = "_AdminLayout";
}

<form asp-controller="qBoSlide" asp-action="Create" method="post" id="slide-form">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.Slide.Create")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.Slide.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = "qBo_slider_slide_create_buttons" })
        </div>
    </div>
    @await Html.PartialAsync("~/Plugins/Widgets.qBoSlider/Views/Admin/Slide/_CreateOrUpdate.cshtml", Model)
</form>

Views/Admin/Slide/CreateSlidePopup.cshtml
@model SlideModel

@{
    Layout = "_AdminPopupLayout";
}

@using Nop.Plugin.Widgets.qBoSlider.Models;

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Common.AddNew")
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
        </div>
    </div>

    @Html.Partial("~/Plugins/Widgets.qBoSlider/Views/Admin/_CreateOrUpdate.cshtml", Model)
}

Views/Admin/Slide/Edit.cshtml
@model SlideModel

@{
    //page title
    ViewBag.Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.Slide.Edit").Text;
    //active menu item (system name)
    nopHtml.SetActiveMenuItemSystemName("Baroque-qBoSlider-Slide");
    Layout = "~/Plugins/Widgets.qBoSlider/Views/Admin/_qBoLayout.cshtml";
}

<form asp-controller="qBoSlide" asp-action="Edit" method="post" id="slide-form">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.Slide.Edit")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.Slide.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="slide-delete" class="btn btn-danger">
                <i class="far fa-trash-alt"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = "qBo_slider_slide_edit_buttons" })
        </div>
    </div>
    @await Html.PartialAsync("~/Plugins/Widgets.qBoSlider/Views/Admin/Slide/_CreateOrUpdate.cshtml", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="slide-delete" />

Views/Admin/Slide/EditSlidePopup.cshtml
@model SlideModel

@{
    Layout = "_AdminPopupLayout";
}

@using Nop.Plugin.Widgets.qBoSlider.Models;

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Common.Edit")
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
        </div>
    </div>
    
    @Html.Partial("~/Plugins/Widgets.qBoSlider/Views/Admin/_CreateOrUpdate.cshtml", Model)
}

Views/Admin/Slide/EditSlideWidgetZonePopup.cshtml
@model EditSlideWidgetZoneModel

@using Nop.Web.Framework.Extensions

@{
    Layout = "_AdminPopupLayout";

    //page title
    ViewBag.Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.Slide.EditSlideWidgetZonePopup").Text;
}

@if (ViewBag.RefreshPage == true)
{
    <script>
        try {window.opener.document.forms['@(Context.Request.Query["formId"])'].@(Context.Request.Query["btnId"]).click();}
        catch (e){}
        window.close();
    </script>
}

<form asp-controller="qBoSlide" asp-action="EditSlideWidgetZonePopup"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.Slide.EditSlideWidgetZonePopup.Details")
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = "qBo_slider_slide_widget_zone_edit_buttons", additionalData = Model })
        </div>
    </div>
    <input asp-for="Id" type="hidden" />
    <input asp-for="SlideId" type="hidden" />
    <section class="content">
        <div class="form-horizontal">
            <div class="cards-group">
                @await Component.InvokeAsync("AdminWidget", new { widgetZone = "qBo_slider_slide_widget_zone_edit_details_top", additionalData = Model })
                <div class="card card-default card-popup">
                    <div class="card-body">
                        <div class="form-group row">
                            <div class="col-sm-3">
                                <nop-label asp-for="WidgetZoneId" />
                            </div>
                            <div class="col-sm-9">
                                <nop-select asp-for="WidgetZoneId" asp-items="@Model.AvailableWidgetZones" />
                            </div>
                        </div>
                        @(await Html.LocalizedEditorAsync<EditSlideWidgetZoneModel, EditSlideWidgetZoneModel.LocalizationModel>("slide-widget-zone-localized",@<div>
                                <div class="form-group row">
                                    <div class="col-sm-3">
                                        <nop-label asp-for="@Model.Locales[item].OverrideDescription" />
                                    </div>
                                    <div class="col-sm-9">
                                        <nop-textarea asp-for="@Model.Locales[item].OverrideDescription" />
                                        <span asp-validation-for="@Model.Locales[item].OverrideDescription"></span>
                                    </div>
                                </div>
                                <input type="hidden" asp-for="@Model.Locales[item].LanguageId" />
                            </div>,@<div>
                                <div class="form-group row">
                                    <div class="col-sm-3">
                                        <nop-label asp-for="OverrideDescription" />
                                    </div>
                                    <div class="col-sm-9">
                                        <nop-textarea asp-for="OverrideDescription" asp-required="true" />
                                        <span asp-validation-for="OverrideDescription"></span>
                                    </div>
                                </div>
                            </div>))
                    </div>
                </div>
                @await Component.InvokeAsync("AdminWidget", new { widgetZone = "qBo_slider_slide_widget_zone_edit_details_bottom", additionalData = Model })
            </div>
        </div>
    </section>
</form>